### ISSUE TITLE
Ability to animate parameters

### ISSUE THREAD

**Issue by bloodychrome** [WiresoulStudio/Wonder_Mesh#1]
Great addon, very useful, thanks! I have one issue/feature request at this time, and it is the ability to animate the parameters, either directly or via animation nodes. Is this currently possible? If not, I'd love to see it as a feature. Keep up the good work.

**Comment by WiresoulStudio** [comment]
Thanks.
Unfortunately, the animation of the parameters is not possible for now. :/
But It's definitely something I would like to do in a future version.
So far there is a workaround with Animation nodes, where you can use "Attribute output" node:
![untitled](https://user-images.githubusercontent.com/16396330/30814983-07c1a9fe-a212-11e7-8cbf-902fbcb55ca4.jpg)
