### ISSUE TITLE
No Cone

### ISSUE THREAD

**Issue by hansnolte** [WiresoulStudio/Wonder_Mesh#2]
Awesome addon!

A little Bug (I think),  the Cone does not appear in the menu.

I hope you will expand this wonderful addon still further.

Many Thanks and Regards
Hans

**Comment by WiresoulStudio** [comment]
Not a bug. I've just didn't write the Cone yet. Don't worry, the addon will expand soon :-)

**Comment by hansnolte** [comment]
Great News.
I'm really looking forward to it.
